import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[scrolling]
history = 10000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 12.0

[window]
opacity = 0.9
padding.x = 6
padding.y = 6
